### ISSUE TITLE
JDK Wrapper fails cryptically when not setting JDKW_DIST

### ISSUE THREAD

**Issue by maximann** [KoskiLabs/jdk-wrapper#5]
When not setting "JDKW_DIST" the wrapper fails with a cryptic error:

[01:09:48] ERROR: curl  -f -k -L -o "/var/tmp/builder.cache/jdk/jdkw//jdkw-impl.sh" "https://github.com/KoskiLabs/jdk-wrapper/releases/download//jdkw-impl.sh" failed with 127

It would be nice to explicitly check for absence instead and error out before attempting the curl.

**Comment by vjkoskela** [comment]
Yes, the error handling needs to be improved. I’ll take care of that. Do you know why it failed to detect the version? Do you have the complete verbose output?

**Comment by vjkoskela** [comment]
So I've been unable to reproduce the error with no JDKW_DIST specified; instead I get this:

```
> ./jdk-wrapper.sh JDKW_DIST= java -version
[18:18:28] Unsupported distribution
```

The error you printed is coming from `jdk-wrapper.sh` trying to download the implementation (`jdkw-impl.sh`). It happens when the script failed to determine the latest release (or have `JDKW_RELEASE`) set. What value do you have for `JDKW_RELEASE`?

If you are using `latest` (or default) for `JDKW_RELEASE` then the script curls Github to determine the latest release before invoking that release. Did invoke the script without internet connectivity?

I'm adding a better warning if the latest fails to resolve, which I think is the case here because if the `//` in the URI. However, I'd like to understand why it failed to resolve. If you could reply with answer to the two questions above as well as any additional output prior to the error, that would be helpful.

**Comment by maximann** [comment]
I've just tried to reproduce this and was no longer able to with the newest version. I also verified that everything works as expected on Darwin. Thanks for following up so promptly.
